/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c dashdb_adaptor -a dashdb_adaptor.h:dashdb_adaptor.cpp dashdb.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DASHDB_ADAPTOR_H_1379606591
#define DASHDB_ADAPTOR_H_1379606591

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.dash.brlcarowa.desktop
 */
class dashdb_adaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.owadash")

public:
    dashdb_adaptor(QObject *parent);
    virtual ~dashdb_adaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void notify(const QString &panel, const QString &widget, const QString &predicate);
Q_SIGNALS: // SIGNALS
    void clicked(const QString &widget);
};

#endif
