/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c dashdbIfAdaptor -a dashdb_iface.h:dashdb_iface.cpp dashdb.xml
 *
 * qdbusxml2cpp is Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DASHDB_IFACE_H_1379622455
#define DASHDB_IFACE_H_1379622455

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.zirexix.carowa
 */
class dashdbIfAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.zirexix.carowa")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.zirexix.carowa\">\n"
"    <method name=\"notify\">\n"
"      <annotation value=\"QVariantMap\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"name\"/>\n"
"      <arg direction=\"in\" type=\"a{sv}\" name=\"customdata\"/>\n"
"    </method>\n"
"    <method name=\"clicked\"/>\n"
"    <signal name=\"user_click\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"eventkind\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    dashdbIfAdaptor(QObject *parent);
    virtual ~dashdbIfAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void clicked();
    void notify(const QString &name, const QVariantMap &customdata);
Q_SIGNALS: // SIGNALS
    void user_click(const QString &eventkind);
};

#endif
