######################################################################
# Automatically generated by qmake (2.01a) ?? ???. 30 15:18:39 2014
######################################################################

TEMPLATE = subdirs

include(config.pri)

shared.files = QtRadio/*
shared.path = $${SHARE_DIR}

docs.files = AUTHORS COPYING ChangeLog INSTALL README TODO DOC/*
docs.path = /usr/doc/qtradio-$${VERSION}

SUBDIRS = src

INSTALLS += shared docs